import React from 'react';
import './ProductsInfoSection.css';

const ProductsInfoSection = () => (
  <section className="products-info-section">
    <h2 className="products-info-title">ÜRÜNLERİMİZ HAKKINDA</h2>
    <p className="products-info-desc">
      Dökme hammadde proseslerinde kullanılan sistemlerin doğru seçilmesi ve kullanılması üretim hatlarının sağlıklı işleyebilmesi için elzemdir. Polimak'ın tecrübeli mühendislik ekibi, sistem tasarım ve seçimlerini endüstriyel uygulamanın gerekliliklerine göre optimize etmektedir. En küçük ekipmandan anahtar teslim hammadde otomasyonuna kadar bütün bileşenler detaylı mühendislik hesapları ile geliştirilmektedir. Standart ekipmanların dışındaki ihtiyaçlar için mühendislik kadromuz özel tasarımlar yaparak projeye özel çözümler sunmaktadır. Firma bünyesinde bulunan Ar-Ge ekibimiz, yeni trendleri ve müşteri beklentilerini sürekli izleyerek, ileri teknolojiye sahip, katma değeri yüksek, gelişen dünyanın ihtiyacı olan endüstriyel çözümleri kısa sürede üretecek altyapıya sahiptir.
    </p>
    <h3 className="products-info-subtitle">Polimak tarafından üretilen ekipman ve sistemler:</h3>
    <div className="products-info-list">
      <p>Hammadde dolum boşaltma, taşıma ve depolama sistemleri: Toz ve tanecikli yapıdaki malzemelerin endüstriyel prosesler içerisinde çeşitli makinalar veya stok noktaları arasındaki aktarımı, üretim hatlarının beslenmesi, depolanması, takibi ve otomasyonu gibi işlemler bu sistemler ile yapılmaktadır. Söz konusu dökme hammadde elleçleme sistemleri bir çok alt bileşeni, ekipman ve makinaları kapsamaktadır.</p>
      <p><b>Pnömatik taşıma sistemleri:</b><br/>Dökme malzemelerin boru hatları içerisinden hava basıncı veya vakumu ile transfer edilmesi için pnömatik taşıma veya diğer adıyla pnömatik transport sistemlerinden yararlanılmaktadır.</p>
      <p><b>Hava kilidi:</b><br/>Hammaddelerin kendi ağırlığı ile belirlenen hızda hacimsel olarak boşaltılmasını sağlamaktadır. Hava kilidi veya diğer adıyla hücre tekeri silo, bunker, filtre gibi ekipmanların altına yerleştirilmektedir.</p>
      <p><b>Jet filtre:</b><br/>Tozlu hammaddelerin aktarım, yükleme, dolum veya boşaltılması sırasında oluşan tozların çevreye yayılmasını önlemek için jet filtre ve toz toplama sistemlerinden yararlanılmaktadır. Tozsuzlaştırma sistemlerinde hava içerisinde bulunan toz partikülleri toplanır, belli bir noktada biriktirilir, temizlenen hava tahliye edilir.</p>
      <p><b>Çuval ve torba boşaltma sistemleri:</b><br/>Un, çimento, buğday, şeker gibi toz ve tanecikli yapıdaki malzemeler genellikle nakliye kolaylığı amacıyla çuval veya torbalar içerisinde taşınmaktadır. Ürünün kullanılacağı noktada çuvalın açılması ve içeriğinin mikser, bunker, konveyör gibi ekipmanlara boşaltılması gerekmektedir. Çuval boşaltma sistemleri ürünün boşaltılması sırasında oluşan tozları ve dışarıdan yabancı maddelerin karışmasını önlemektedir. Temiz ve sağlıklı bir yükleme sağlamaktadır.</p>
      <p><b>Big Bag boşaltma sistemleri:</b><br/>Yüksek hacimli üretim tesislerinde çuval ile gelen hammaddeyi yönetmek zorlaşmaktadır. Büyük boyutlu bir çuval olan bigbagler genellikle bir seferde 500kg-2000kg arasında hammaddeyi taşıyabilecek boyuttadır. Bu boyutları ile daha kısa sürede daha fazla hammaddenin aktarımını ve işlenmesini sağlamaktadır. Big bag boşaltma sistemleri yardımıyla yüksek miktardaki hammaddeler big bag çuvallardan kolay ve güvenli bir yöntemle boşaltılmakta ve bir sonraki proses ekipmanına aktarılmaktadır.</p>
      <p><b>Teleskopik dolum körükleri:</b><br/>Toz hammaddelerin dökme halde sevk edilmesi için kamyon, silobas, gemi veya vagonlara yüklenmesi sırasında ortama önemli miktarda toz yayılmakta ve ürün kaybı olmaktadır. Teleskopik yükleme körükleri ile malzemenin dolumu sırasında oluşan toz önlenmekte, yükleme operasyonunun verimi arttırılmaktadır. Teleskopik Yükleme sistemleri ile ilgili sayfamız için tıklayınız.</p>
      <p><b>Blower – Hava Körüğü :</b><br/>Pnömatik taşıma, atık su arıtma, vakum sistemleri gibi bir çok endüstriyel proseste gerekli olan yüksek debili ve orta basınçlı hava ihtiyacında hava körükleri kullanılmaktadır. Roots blower olarak ta adlandırılan hava körüğü pozitif deplasman prensibiyle çalışan çift rotordan oluşan hava ve gaz pompalarıdır.</p>
      <p><b>Akış yönlendirme ve kontrol vanası, klepeler :</b><br/>Dökme malzemelerin çeşitli proses hatları arasında akışının kontrolü ve yönlendirilmesi amacıyla kontrol vanaları ve klepelerden yararlanılmaktadır. Yerçekimi yardımıyla dikey akan malzemeler pantolon klepe gibi vanalarda iki veya daha çok noktaya yönlendirilmektedir. Pnömatik sevk sistemlerinde ise basınçlı boru hattı içerisinde istenilen boru hattına yönlendirilmektedir. Kelebek klepe, sürgülü veya bıçaklı vanalar ise akışın tam açılması veya kesilmesinde kullanılmaktadır.</p>
      <p><b>Helezon konveyör ve besleyiciler :</b><br/>Helezon konveyörler, yakın iki nokta arasında malzeme transferini sağlayan en basit aktarım organlarıdır. Kapalı bir tüp veya U kesitli hazne içerisinde dönen spiral şeklindeki yapraklar yardımıyla malzeme ileri doğru sürülür. Çimento, kalsit, PVC, un, gibi toz halindeki malzemelerin aktarımında kullanıldığı gibi, polietilen, polipropilen, mısır, buğday gibi granül veya tanecikli yapıdaki malzemelerin sevkinde de ekonomik bir çözüm sunar.</p>
      <p><b>Hammadde Siloları :</b><br/>Hammadde depolama siloları kuru dökme malzemelerin geçici olarak depolanmasını sağlar. Silo gövdesi genellikle silindirik ve dikey yapıdadır, çıkış ağzı konik şeklindedir. Proses ihtiyacına göre tek bir silo ile depolama ihtiyaçları karşılanacağı gibi, çok sayıda silodan, dolum ve boşaltma hatlarından oluşan silo sistemleri ile birlikte lojistik ve depolama ihtiyaçlarına kapsamlı bir çözüm getirilmektedir.</p>
      <p><b>Silo ekipmanları, kontrol ve güvenlik sistemleri :</b><br/>Hammadde depolama siloları ile içlerinde depolanan malzemelerin durumunun takibi ve idaresi için çeşitli sistemler kullanılmaktadır. Silo içerisindeki malzeme seviyesi, ağırlığı, sıcaklık ve nem bilgisi gibi veriler depolanan hammaddenin durumu hakkında tesis sorumlularına bilgi verir. Bunun dışında siloya bağlanan konveyör, jet filtre, emniyet valfi gibi ekipmanların kontrolleri bu sistemler ile sağlanır.</p>
      <p><b>Seyyar big bag boşaltma ve silobas dolum sistemi :</b><br/>Büyük lojistik operasyonlarında big bag içerisinde bulunan malzemelerin silobaslara doldurulması gerektiğinde seyyar bigbag boşaltma ve silobas yükleme sistemlerinden yararlanılmaktadır. Kuru dökme malzemeler big bag içerisinden bu sistem yardımıyla boşaltılmakta, tozsuz olarak silobaslara veya açık kamyonlara doldurulmaktadır.</p>
      <p><b>Kül taşıma, tahliye ve depolama sistemleri:</b><br/>Kömür veya katı atık yakan enerji santrallerinde yanan malzemenin artığı olan külün güvenli bir yöntemle kazanlardan uzaklaştırılması ve depolanması gerekmektedir. Kazan çıkışında, ekonomizer veya torbalı filtrede biriken kül sıcak halde iken boşaltılmakta ve pnömatik sevk sistemi yardımıyla silolara aktarılmaktadır. Silo altına yanaşan silobaslar ile bertaraf veya geri dönüşüm amacıyla ilgili tesislere gönderilmektedir.</p>
    </div>
  </section>
);

export default ProductsInfoSection; 